appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: O47ft9XQhwybdZyZLDZSbLAhoz3tkIZZQPS+MsR+NslOGXWXBWHdtwSfy/33NJCBibiA+CBPkcixZqTgccQYmS0m8XY1616fJNUrkQBmGKf9L5887EYNTOXSq8S+kFCg2QnkdF57lSJy5NCLUeZIsbMox76FqzgVLi1otwNMyRJRwEmrLI0mT2/IIojKwk+Mt+Ashegc0Vg18aI69Q1+Q0drdieJnzZi1h/ZB86IpvPqCI+D/MR+7uizgprs1N1TXnAfMK+ACK17PMLdcs7wi2iFV0VIoO7DsPGliN/xjkuCiXUqT/e8ZovOx6eLl+VibC65QcmV0Vq/m7LorxznML4LOcMARhL42BuWoOJWD4IOqKs5XZnjFBbhbZCPVvfi3OUgIJMVPetK+4lnKDbZwHW7fgUE/D1lZfhBLskYj8ijPVltsGsNIhRZ6CAXyjjo2YLiDG6I3vfHF1XfMjHG7XkmB1gRMMQGjd761OtTy384b0dAYnXVbG3VyMPRvHT84vWnlwLjNROLSwwW86kLmj38rjLxDDsS8SqYpYbyzAtdc2T0LxlQkw4AJwst+/MwdSdhOlp3NveJU30m8x/XBmxkbxRj0alROq1GO/eGLhS/Kq4+veo+fjkZUw6cYHiYzUFsmtf4xlsFhcq/DED8XiOsYrrosNSW3lJZ1004mW4=}
bot:
  automerge: true
